language: java
jdk:
  - oraclejdk7
  - openjdk7
before_script:
  - psql -c "create user chouette with login createdb encrypted password 'chouette';" -U postgres
  - psql -c 'create database chouette_val_test with owner = chouette;' -U postgres
